import type { ScenarioDefinition } from '../types/scenario';

export const coldwarGlobal: ScenarioDefinition = {
  id: 'coldwar-global',
  era: '冷戰',
  region: '全球',
  nameZh: '冷戰全球',
  description: '冷戰時期(1955年)全球對抗。北約對抗華約,美蘇兩極爭霸。',
  mapBounds: [[-180, -60], [180, 80]],
  countries: [
    { id: 'usa', name: 'United States', nameZh: '美利堅合眾國', code: 'USA', color: '#3c3b6e', side: 'entente', capital: 'Washington', capitalZh: '華盛頓', flagIcon: '🇺🇸', tier: 'major' },
    { id: 'gbr', name: 'United Kingdom', nameZh: '大不列顛及北愛爾蘭聯合王國', code: 'GBR', color: '#00247d', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇬🇧', tier: 'major' },
    { id: 'fra', name: 'French Republic', nameZh: '法蘭西共和國', code: 'FRA', color: '#0055a5', side: 'entente', capital: 'Paris', capitalZh: '巴黎', flagIcon: '🇫🇷', tier: 'major' },
    { id: 'deu_w', name: 'West Germany', nameZh: '德意志聯邦共和國', code: 'FRG', color: '#1a1a1a', side: 'entente', capital: 'Bonn', capitalZh: '波恩', flagIcon: '🇩🇪', tier: 'major' },
    { id: 'ita', name: 'Italian Republic', nameZh: '義大利共和國', code: 'ITA', color: '#009246', side: 'entente', capital: 'Rome', capitalZh: '羅馬', flagIcon: '🇮🇹', tier: 'secondary' },
    { id: 'can', name: 'Canada', nameZh: '加拿大', code: 'CAN', color: '#ff0000', side: 'entente', capital: 'Ottawa', capitalZh: '渥太華', flagIcon: '🇨🇦', tier: 'secondary' },
    { id: 'tur', name: 'Turkey', nameZh: '土耳其共和國', code: 'TUR', color: '#e30a17', side: 'entente', capital: 'Ankara', capitalZh: '安卡拉', flagIcon: '🇹🇷', tier: 'secondary' },
    { id: 'grc', name: 'Greece', nameZh: '希臘王國', code: 'GRC', color: '#0d5eaf', side: 'entente', capital: 'Athens', capitalZh: '雅典', flagIcon: '🇬🇷', tier: 'minor' },
    { id: 'jpn', name: 'Japan', nameZh: '日本國', code: 'JPN', color: '#bc002d', side: 'entente', capital: 'Tokyo', capitalZh: '東京', flagIcon: '🇯🇵', tier: 'major' },
    { id: 'kor_s', name: 'South Korea', nameZh: '大韓民國', code: 'KOR', color: '#003478', side: 'entente', capital: 'Seoul', capitalZh: '首爾', flagIcon: '🇰🇷', tier: 'secondary' },
    { id: 'irn', name: 'Iran', nameZh: '伊朗帝國', code: 'IRN', color: '#239f40', side: 'entente', capital: 'Tehran', capitalZh: '德黑蘭', flagIcon: '🇮🇷', tier: 'secondary' },
    { id: 'isr', name: 'Israel', nameZh: '以色列國', code: 'ISR', color: '#2a5f9f', side: 'entente', capital: 'Tel Aviv', capitalZh: '特拉維夫', flagIcon: '🇮🇱', tier: 'minor' },
    { id: 'pak', name: 'Pakistan', nameZh: '巴基斯坦伊斯蘭共和國', code: 'PAK', color: '#01411c', side: 'entente', capital: 'Karachi', capitalZh: '卡拉奇', flagIcon: '🇵🇰', tier: 'secondary' },
    { id: 'aus', name: 'Australia', nameZh: '澳大利亞', code: 'AUS', color: '#00008b', side: 'entente', capital: 'Canberra', capitalZh: '坎培拉', flagIcon: '🇦🇺', tier: 'secondary' },
    { id: 'sov', name: 'Soviet Union', nameZh: '蘇維埃社會主義共和國聯盟', code: 'SUN', color: '#cc0000', side: 'central', capital: 'Moscow', capitalZh: '莫斯科', flagIcon: '🇷🇺', tier: 'major' },
    { id: 'deu_e', name: 'East Germany', nameZh: '德意志民主共和國', code: 'GDR', color: '#444444', side: 'central', capital: 'East Berlin', capitalZh: '東柏林', flagIcon: '🇩🇪', tier: 'secondary' },
    { id: 'pol', name: 'Poland', nameZh: '波蘭人民共和國', code: 'POL', color: '#dc143c', side: 'central', capital: 'Warsaw', capitalZh: '華沙', flagIcon: '🇵🇱', tier: 'secondary' },
    { id: 'cze', name: 'Czechoslovakia', nameZh: '捷克斯洛伐克社會主義共和國', code: 'CZE', color: '#11457e', side: 'central', capital: 'Prague', capitalZh: '布拉格', flagIcon: '🇨🇿', tier: 'secondary' },
    { id: 'hun', name: 'Hungary', nameZh: '匈牙利人民共和國', code: 'HUN', color: '#477050', side: 'central', capital: 'Budapest', capitalZh: '布達佩斯', flagIcon: '🇭🇺', tier: 'minor' },
    { id: 'rou', name: 'Romania', nameZh: '羅馬尼亞人民共和國', code: 'ROU', color: '#002b7f', side: 'central', capital: 'Bucharest', capitalZh: '布加勒斯特', flagIcon: '🇷🇴', tier: 'minor' },
    { id: 'bgr', name: 'Bulgaria', nameZh: '保加利亞人民共和國', code: 'BGR', color: '#00966e', side: 'central', capital: 'Sofia', capitalZh: '索非亞', flagIcon: '🇧🇬', tier: 'minor' },
    { id: 'yug', name: 'Yugoslavia', nameZh: '南斯拉夫社會主義聯邦共和國', code: 'YUG', color: '#0b40d0', side: 'neutral', capital: 'Belgrade', capitalZh: '貝爾格勒', flagIcon: '🇷🇸', tier: 'secondary' },
    { id: 'chn', name: "China (PRC)", nameZh: '中華人民共和國', code: 'CHN', color: '#de2910', side: 'central', capital: 'Beijing', capitalZh: '北京', flagIcon: '🇨🇳', tier: 'major' },
    { id: 'kor_n', name: 'North Korea', nameZh: '朝鮮民主主義人民共和國', code: 'PRK', color: '#024fa2', side: 'central', capital: 'Pyongyang', capitalZh: '平壤', flagIcon: '🇰🇵', tier: 'minor' },
    { id: 'vnm_n', name: 'North Vietnam', nameZh: '越南民主共和國', code: 'VNM', color: '#da251d', side: 'central', capital: 'Hanoi', capitalZh: '河內', flagIcon: '🇻🇳', tier: 'minor' },
    { id: 'cub', name: 'Cuba', nameZh: '古巴共和國', code: 'CUB', color: '#002a8f', side: 'central', capital: 'Havana', capitalZh: '哈瓦那', flagIcon: '🇨🇺', tier: 'minor' },
    { id: 'ind', name: 'India', nameZh: '印度共和國', code: 'IND', color: '#ff9933', side: 'neutral', capital: 'New Delhi', capitalZh: '新德里', flagIcon: '🇮🇳', tier: 'major' },
    { id: 'idn', name: 'Indonesia', nameZh: '印度尼西亞共和國', code: 'IDN', color: '#ff0000', side: 'neutral', capital: 'Jakarta', capitalZh: '雅加達', flagIcon: '🇮🇩', tier: 'secondary' },
    { id: 'egy', name: 'Egypt', nameZh: '埃及共和國', code: 'EGY', color: '#c80315', side: 'neutral', capital: 'Cairo', capitalZh: '開羅', flagIcon: '🇪🇬', tier: 'secondary' },
    { id: 'bra', name: 'Brazil', nameZh: '巴西聯邦共和國', code: 'BRA', color: '#009c3b', side: 'neutral', capital: 'Brasília', capitalZh: '巴西利亞', flagIcon: '🇧🇷', tier: 'secondary' },
    { id: 'arg', name: 'Argentina', nameZh: '阿根廷共和國', code: 'ARG', color: '#75aadb', side: 'neutral', capital: 'Buenos Aires', capitalZh: '布宜諾斯艾利斯', flagIcon: '🇦🇷', tier: 'secondary' },
    { id: 'mex', name: 'Mexico', nameZh: '墨西哥合眾國', code: 'MEX', color: '#006847', side: 'neutral', capital: 'Mexico City', capitalZh: '墨西哥城', flagIcon: '🇲🇽', tier: 'secondary' },
    { id: 'sau', name: 'Saudi Arabia', nameZh: '沙烏地阿拉伯王國', code: 'SAU', color: '#006c35', side: 'neutral', capital: 'Riyadh', capitalZh: '利雅德', flagIcon: '🇸🇦', tier: 'secondary' },
    { id: 'esp', name: 'Spain', nameZh: '西班牙國', code: 'ESP', color: '#aa151b', side: 'neutral', capital: 'Madrid', capitalZh: '馬德里', flagIcon: '🇪🇸', tier: 'secondary' },
    { id: 'swe', name: 'Sweden', nameZh: '瑞典王國', code: 'SWE', color: '#006aa7', side: 'neutral', capital: 'Stockholm', capitalZh: '斯德哥爾摩', flagIcon: '🇸🇪', tier: 'minor' },
    { id: 'che', name: 'Switzerland', nameZh: '瑞士聯邦', code: 'CHE', color: '#d52b1e', side: 'neutral', capital: 'Bern', capitalZh: '伯恩', flagIcon: '🇨🇭', tier: 'minor' },
    { id: 'afg', name: 'Afghanistan', nameZh: '阿富汗王國', code: 'AFG', color: '#003893', side: 'neutral', capital: 'Kabul', capitalZh: '喀布爾', flagIcon: '🇦🇫', tier: 'minor' },
  ],
  territoryMap: {
    // NATO / Western bloc
    'US':'usa','GB':'gbr','IE':'gbr','FR':'fra',
    'DE':'deu_w','IT':'ita','SM':'ita','CA':'can','TR':'tur','SY':'tur','GR':'grc',
    'JP':'jpn','KR':'kor_s','IR':'irn','IL':'isr','PS':'isr','JO':'isr','PK':'pak','BD':'pak',
    'AU':'aus','PG':'aus','NZ':'aus','FJ':'aus','SB':'aus',
    'ES':'esp','PT':'esp','NL':'deu_w','BE':'deu_w','LU':'deu_w','DK':'deu_w','NO':'deu_w','IS':'usa',
    // Soviet bloc
    'RU':'sov','UA':'sov','BY':'sov','LT':'sov','LV':'sov','EE':'sov','MD':'sov','KZ':'sov','UZ':'sov','TM':'sov','KG':'sov','TJ':'sov','AZ':'sov','AM':'sov','GE':'sov',
    'PL':'pol','CZ':'cze','SK':'cze','HU':'hun','RO':'rou','BG':'bgr','AL':'sov',
    // East Germany
    // (DE is split — can't do by iso2 alone, but for simplicity DE->west, east germany uses separate handling)
    // Non-aligned
    'CN':'chn','TW':'chn','HK':'chn','MO':'chn',
    'KP':'kor_n',
    'VN':'vnm_n','LA':'vnm_n','KH':'vnm_n',
    'CU':'cub',
    'IN':'ind','LK':'ind','BT':'ind','NP':'ind','MM':'ind',
    'ID':'idn','MY':'idn','SG':'idn','BN':'idn','TH':'idn',
    'EG':'egy','SD':'egy','SS':'egy','LY':'egy','TN':'egy','DZ':'egy','MA':'egy',
    'BR':'bra','AR':'arg','CL':'arg','UY':'arg','PY':'bra','BO':'bra',
    'MX':'mex','GT':'mex','BZ':'mex','HN':'mex','SV':'mex','NI':'mex','CR':'mex','PA':'mex',
    'SA':'sau','AE':'sau','OM':'sau','YE':'sau','QA':'sau','BH':'sau','KW':'sau',
    'SE':'swe','CH':'che','FI':'swe','AF':'afg',
    // African nations -> nearest bloc
    'ZA':'gbr','NA':'gbr','ZW':'gbr','ZM':'gbr','BW':'gbr','LS':'gbr','MW':'gbr','MZ':'gbr',
    'NG':'gbr','GH':'gbr','SL':'gbr','GM':'gbr','LR':'usa',
    'KE':'gbr','UG':'gbr','TZ':'gbr','SO':'gbr','ET':'usa','ER':'sov',
    'CM':'fra','GA':'fra','CG':'fra','CD':'fra','TG':'fra','BJ':'fra','BF':'fra','ML':'fra','SN':'fra','GN':'fra','CI':'fra','NE':'fra','MR':'fra','CF':'fra','TD':'fra','MG':'fra','KM':'fra','DJ':'fra',
    'AO':'sov','MZ2':'sov','GH2':'sov',
    'CO':'usa','VE':'usa','PE':'usa','EC':'usa',
    '-1':'usa',
  },
};
