import type { ScenarioDefinition } from '../types/scenario';

export const wwiEurope: ScenarioDefinition = {
  id: 'wwi-europe',
  era: '一戰',
  region: '歐洲',
  nameZh: '一戰歐洲',
  description: '1914年歐洲戰場。協約國對抗同盟國,從西線到巴爾幹。',
  mapBounds: [[-25, 34], [45, 71]],
  countries: [
    { id: 'deu', name: 'German Empire', nameZh: '德意志帝國', code: 'DEU', color: '#333333', side: 'central', capital: 'Berlin', capitalZh: '柏林', flagIcon: '🇩🇪', tier: 'major' },
    { id: 'aut', name: 'Austro-Hungarian Empire', nameZh: '奧匈帝國', code: 'AUT', color: '#c41e3a', side: 'central', capital: 'Vienna', capitalZh: '維也納', flagIcon: '🇦🇹', tier: 'major' },
    { id: 'tur', name: 'Ottoman Empire', nameZh: '奧斯曼帝國', code: 'TUR', color: '#e30a17', side: 'central', capital: 'Constantinople', capitalZh: '君士坦丁堡', flagIcon: '🇹🇷', tier: 'major' },
    { id: 'bgr', name: 'Kingdom of Bulgaria', nameZh: '保加利亞王國', code: 'BGR', color: '#00966e', side: 'central', capital: 'Sofia', capitalZh: '索非亞', flagIcon: '🇧🇬', tier: 'secondary' },
    { id: 'gbr', name: 'United Kingdom', nameZh: '大英帝國', code: 'GBR', color: '#00247d', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇬🇧', tier: 'major' },
    { id: 'fra', name: 'French Republic', nameZh: '法蘭西共和國', code: 'FRA', color: '#0055a5', side: 'entente', capital: 'Paris', capitalZh: '巴黎', flagIcon: '🇫🇷', tier: 'major' },
    { id: 'rus', name: 'Russian Empire', nameZh: '俄羅斯帝國', code: 'RUS', color: '#0039a6', side: 'entente', capital: 'Petrograd', capitalZh: '彼得格勒', flagIcon: '🇷🇺', tier: 'major' },
    { id: 'ita', name: 'Kingdom of Italy', nameZh: '義大利王國', code: 'ITA', color: '#009246', side: 'entente', capital: 'Rome', capitalZh: '羅馬', flagIcon: '🇮🇹', tier: 'major' },
    { id: 'srb', name: 'Kingdom of Serbia', nameZh: '塞爾維亞王國', code: 'SRB', color: '#0c4076', side: 'allies', capital: 'Belgrade', capitalZh: '貝爾格勒', flagIcon: '🇷🇸', tier: 'secondary' },
    { id: 'bel', name: 'Kingdom of Belgium', nameZh: '比利時王國', code: 'BEL', color: '#ffd100', side: 'allies', capital: 'Brussels', capitalZh: '布魯塞爾', flagIcon: '🇧🇪', tier: 'secondary' },
    { id: 'rou', name: 'Kingdom of Romania', nameZh: '羅馬尼亞王國', code: 'ROU', color: '#002b7f', side: 'allies', capital: 'Bucharest', capitalZh: '布加勒斯特', flagIcon: '🇷🇴', tier: 'secondary' },
    { id: 'grc', name: 'Kingdom of Greece', nameZh: '希臘王國', code: 'GRC', color: '#0d5eaf', side: 'allies', capital: 'Athens', capitalZh: '雅典', flagIcon: '🇬🇷', tier: 'secondary' },
    { id: 'mne', name: 'Montenegro', nameZh: '蒙特內哥羅王國', code: 'MNE', color: '#c8102e', side: 'allies', capital: 'Cetinje', capitalZh: '采蒂涅', flagIcon: '🇲🇪', tier: 'minor' },
    { id: 'prt', name: 'Portugal', nameZh: '葡萄牙王國', code: 'PRT', color: '#046a38', side: 'allies', capital: 'Lisbon', capitalZh: '里斯本', flagIcon: '🇵🇹', tier: 'minor' },
    { id: 'esp', name: 'Spain', nameZh: '西班牙王國', code: 'ESP', color: '#aa151b', side: 'neutral', capital: 'Madrid', capitalZh: '馬德里', flagIcon: '🇪🇸', tier: 'secondary' },
    { id: 'nld', name: 'Netherlands', nameZh: '荷蘭王國', code: 'NLD', color: '#21468b', side: 'neutral', capital: 'Amsterdam', capitalZh: '阿姆斯特丹', flagIcon: '🇳🇱', tier: 'minor' },
    { id: 'swe', name: 'Sweden', nameZh: '瑞典王國', code: 'SWE', color: '#006aa7', side: 'neutral', capital: 'Stockholm', capitalZh: '斯德哥爾摩', flagIcon: '🇸🇪', tier: 'minor' },
    { id: 'nor', name: 'Norway', nameZh: '挪威王國', code: 'NOR', color: '#ba0c2f', side: 'neutral', capital: 'Oslo', capitalZh: '奧斯陸', flagIcon: '🇳🇴', tier: 'minor' },
    { id: 'dnk', name: 'Denmark', nameZh: '丹麥王國', code: 'DNK', color: '#c8102e', side: 'neutral', capital: 'Copenhagen', capitalZh: '哥本哈根', flagIcon: '🇩🇰', tier: 'minor' },
    { id: 'che', name: 'Switzerland', nameZh: '瑞士聯邦', code: 'CHE', color: '#d52b1e', side: 'neutral', capital: 'Bern', capitalZh: '伯恩', flagIcon: '🇨🇭', tier: 'minor' },
    { id: 'alb', name: 'Albania', nameZh: '阿爾巴尼亞', code: 'ALB', color: '#e41e20', side: 'neutral', capital: 'Tirana', capitalZh: '地拉那', flagIcon: '🇦🇱', tier: 'minor' },
    { id: 'lux', name: 'Luxembourg', nameZh: '盧森堡大公國', code: 'LUX', color: '#00a3dd', side: 'neutral', capital: 'Luxembourg', capitalZh: '盧森堡', flagIcon: '🇱🇺', tier: 'minor' },
  ],
  territoryMap: {
    'DE':'deu','LU':'deu','AT':'aut','HU':'aut','CZ':'aut','SK':'aut','SI':'aut','HR':'aut','BA':'aut',
    'TR':'tur','SY':'tur','LB':'tur','IL':'tur','PS':'tur','JO':'tur','IQ':'tur','YE':'tur',
    'BG':'bgr','MK':'bgr',
    'GB':'gbr','IE':'gbr','FR':'fra','RU':'rus','FI':'rus','EE':'rus','LV':'rus','LT':'rus','PL':'rus','BY':'rus','UA':'rus','MD':'rus',
    'GE':'rus','AM':'rus','AZ':'rus','KZ':'rus','UZ':'rus','TM':'rus','KG':'rus','TJ':'rus',
    'IT':'ita','SM':'ita','VA':'ita',
    'RS':'srb','ME':'mne','AL':'alb','GR':'grc','RO':'rou',
    'BE':'bel','PT':'prt','ES':'esp','NL':'nld','SE':'swe','NO':'nor','DK':'dnk','CH':'che',
  },
};
