import type { ScenarioDefinition } from '../types/scenario';

export const wwiiEurope: ScenarioDefinition = {
  id: 'wwii-europe',
  era: '二戰',
  region: '歐洲',
  nameZh: '二戰歐洲',
  description: '1939-1945年第二次世界大戰歐洲戰場。軸心國對抗同盟國。',
  mapBounds: [[-25, 34], [45, 71]],
  countries: [
    { id: 'deu', name: 'Nazi Germany', nameZh: '納粹德國', code: 'DEU', color: '#333333', side: 'central', capital: 'Berlin', capitalZh: '柏林', flagIcon: '🇩🇪', tier: 'major' },
    { id: 'ita', name: 'Fascist Italy', nameZh: '法西斯義大利', code: 'ITA', color: '#009246', side: 'central', capital: 'Rome', capitalZh: '羅馬', flagIcon: '🇮🇹', tier: 'major' },
    { id: 'hun', name: 'Kingdom of Hungary', nameZh: '匈牙利王國', code: 'HUN', color: '#477050', side: 'central', capital: 'Budapest', capitalZh: '布達佩斯', flagIcon: '🇭🇺', tier: 'secondary' },
    { id: 'rou', name: 'Kingdom of Romania', nameZh: '羅馬尼亞王國', code: 'ROU', color: '#002b7f', side: 'central', capital: 'Bucharest', capitalZh: '布加勒斯特', flagIcon: '🇷🇴', tier: 'secondary' },
    { id: 'bgr', name: 'Tsardom of Bulgaria', nameZh: '保加利亞沙皇國', code: 'BGR', color: '#00966e', side: 'central', capital: 'Sofia', capitalZh: '索非亞', flagIcon: '🇧🇬', tier: 'secondary' },
    { id: 'fin', name: 'Finland', nameZh: '芬蘭共和國', code: 'FIN', color: '#003580', side: 'central', capital: 'Helsinki', capitalZh: '赫爾辛基', flagIcon: '🇫🇮', tier: 'secondary' },
    { id: 'gbr', name: 'United Kingdom', nameZh: '大英帝國', code: 'GBR', color: '#00247d', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇬🇧', tier: 'major' },
    { id: 'fra', name: 'French Republic', nameZh: '法蘭西共和國', code: 'FRA', color: '#0055a5', side: 'entente', capital: 'Paris', capitalZh: '巴黎', flagIcon: '🇫🇷', tier: 'major' },
    { id: 'sov', name: 'Soviet Union', nameZh: '蘇維埃社會主義共和國聯盟', code: 'SUN', color: '#cc0000', side: 'entente', capital: 'Moscow', capitalZh: '莫斯科', flagIcon: '🇷🇺', tier: 'major' },
    { id: 'usa', name: 'United States', nameZh: '美利堅合眾國', code: 'USA', color: '#3c3b6e', side: 'entente', capital: 'Washington', capitalZh: '華盛頓', flagIcon: '🇺🇸', tier: 'major' },
    { id: 'pol', name: 'Poland', nameZh: '波蘭共和國', code: 'POL', color: '#dc143c', side: 'allies', capital: 'Warsaw', capitalZh: '華沙', flagIcon: '🇵🇱', tier: 'secondary' },
    { id: 'yug', name: 'Yugoslavia', nameZh: '南斯拉夫王國', code: 'YUG', color: '#0b40d0', side: 'allies', capital: 'Belgrade', capitalZh: '貝爾格勒', flagIcon: '🇷🇸', tier: 'secondary' },
    { id: 'grc', name: 'Greece', nameZh: '希臘王國', code: 'GRC', color: '#0d5eaf', side: 'allies', capital: 'Athens', capitalZh: '雅典', flagIcon: '🇬🇷', tier: 'secondary' },
    { id: 'bel', name: 'Belgium', nameZh: '比利時王國', code: 'BEL', color: '#ffd100', side: 'allies', capital: 'Brussels', capitalZh: '布魯塞爾', flagIcon: '🇧🇪', tier: 'minor' },
    { id: 'nld', name: 'Netherlands', nameZh: '荷蘭王國', code: 'NLD', color: '#21468b', side: 'allies', capital: 'Amsterdam', capitalZh: '阿姆斯特丹', flagIcon: '🇳🇱', tier: 'minor' },
    { id: 'nor', name: 'Norway', nameZh: '挪威王國', code: 'NOR', color: '#ba0c2f', side: 'allies', capital: 'Oslo', capitalZh: '奧斯陸', flagIcon: '🇳🇴', tier: 'minor' },
    { id: 'dnk', name: 'Denmark', nameZh: '丹麥王國', code: 'DNK', color: '#c8102e', side: 'allies', capital: 'Copenhagen', capitalZh: '哥本哈根', flagIcon: '🇩🇰', tier: 'minor' },
    { id: 'cze', name: 'Czechoslovakia', nameZh: '捷克斯洛伐克共和國', code: 'CZE', color: '#11457e', side: 'allies', capital: 'Prague', capitalZh: '布拉格', flagIcon: '🇨🇿', tier: 'secondary' },
    { id: 'esp', name: 'Spain', nameZh: '西班牙國', code: 'ESP', color: '#aa151b', side: 'neutral', capital: 'Madrid', capitalZh: '馬德里', flagIcon: '🇪🇸', tier: 'secondary' },
    { id: 'prt', name: 'Portugal', nameZh: '葡萄牙共和國', code: 'PRT', color: '#046a38', side: 'neutral', capital: 'Lisbon', capitalZh: '里斯本', flagIcon: '🇵🇹', tier: 'minor' },
    { id: 'swe', name: 'Sweden', nameZh: '瑞典王國', code: 'SWE', color: '#006aa7', side: 'neutral', capital: 'Stockholm', capitalZh: '斯德哥爾摩', flagIcon: '🇸🇪', tier: 'minor' },
    { id: 'che', name: 'Switzerland', nameZh: '瑞士聯邦', code: 'CHE', color: '#d52b1e', side: 'neutral', capital: 'Bern', capitalZh: '伯恩', flagIcon: '🇨🇭', tier: 'minor' },
    { id: 'irl', name: 'Ireland', nameZh: '愛爾蘭共和國', code: 'IRL', color: '#169b62', side: 'neutral', capital: 'Dublin', capitalZh: '都柏林', flagIcon: '🇮🇪', tier: 'minor' },
    { id: 'tur', name: 'Turkey', nameZh: '土耳其共和國', code: 'TUR', color: '#e30a17', side: 'neutral', capital: 'Ankara', capitalZh: '安卡拉', flagIcon: '🇹🇷', tier: 'secondary' },
  ],
  territoryMap: {
    'DE':'deu','AT':'deu', // Anschluss 1938
    'IT':'ita','SM':'ita',
    'HU':'hun','RO':'rou','BG':'bgr','FI':'fin',
    'GB':'gbr','IE':'irl','FR':'fra',
    'RU':'sov','UA':'sov','BY':'sov','LT':'sov','LV':'sov','EE':'sov','MD':'sov','KZ':'sov','UZ':'sov','TM':'sov','KG':'sov','TJ':'sov','AZ':'sov','AM':'sov','GE':'sov',
    'PL':'pol','CZ':'cze','SK':'cze',
    'RS':'yug','HR':'yug','SI':'yug','BA':'yug','ME':'yug','MK':'yug',
    'GR':'grc','BE':'bel','NL':'nld','NO':'nor','DK':'dnk','SE':'swe','CH':'che',
    'ES':'esp','PT':'prt','TR':'tur','SY':'tur','LB':'tur','IL':'tur','PS':'tur','JO':'tur','IQ':'tur',
  },
};
