import type { ScenarioDefinition } from '../types/scenario';

export const wwiiAsia: ScenarioDefinition = {
  id: 'wwii-asia',
  era: '二戰',
  region: '亞洲',
  nameZh: '二戰亞洲',
  description: '1937-1945年亞洲太平洋戰場。大日本帝國對抗中美英蘇同盟。',
  mapBounds: [[60, -10], [180, 55]],
  countries: [
    { id: 'jpn', name: 'Empire of Japan', nameZh: '大日本帝國', code: 'JPN', color: '#bc002d', side: 'central', capital: 'Tokyo', capitalZh: '東京', flagIcon: '🇯🇵', tier: 'major' },
    { id: 'tha', name: 'Thailand', nameZh: '泰王國', code: 'THA', color: '#a51931', side: 'central', capital: 'Bangkok', capitalZh: '曼谷', flagIcon: '🇹🇭', tier: 'minor' },
    { id: 'chn', name: 'Republic of China', nameZh: '中華民國', code: 'CHN', color: '#de2910', side: 'entente', capital: 'Chongqing', capitalZh: '重慶', flagIcon: '🇨🇳', tier: 'major' },
    { id: 'usa', name: 'United States', nameZh: '美利堅合眾國', code: 'USA', color: '#3c3b6e', side: 'entente', capital: 'Washington', capitalZh: '華盛頓', flagIcon: '🇺🇸', tier: 'major' },
    { id: 'gbr', name: 'British Empire', nameZh: '大英帝國', code: 'GBR', color: '#00247d', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇬🇧', tier: 'major' },
    { id: 'sov', name: 'Soviet Union', nameZh: '蘇聯', code: 'SUN', color: '#cc0000', side: 'entente', capital: 'Moscow', capitalZh: '莫斯科', flagIcon: '🇷🇺', tier: 'major' },
    { id: 'ind', name: 'British Raj', nameZh: '英屬印度', code: 'IND', color: '#ff9933', side: 'entente', capital: 'Delhi', capitalZh: '德里', flagIcon: '🇮🇳', tier: 'secondary' },
    { id: 'aus', name: 'Australia', nameZh: '澳大利亞聯邦', code: 'AUS', color: '#00008b', side: 'entente', capital: 'Canberra', capitalZh: '坎培拉', flagIcon: '🇦🇺', tier: 'secondary' },
    { id: 'nld', name: 'Netherlands', nameZh: '荷蘭王國(流亡政府)', code: 'NLD', color: '#21468b', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇳🇱', tier: 'minor' },
    { id: 'kor_n', name: 'Japanese Korea', nameZh: '日治朝鮮', code: 'JPK', color: '#024fa2', side: 'central', capital: 'Keijo', capitalZh: '京城', flagIcon: '🇰🇷', tier: 'minor' },
    { id: 'fra', name: 'Free France', nameZh: '自由法國', code: 'FRA', color: '#0055a5', side: 'entente', capital: 'London', capitalZh: '倫敦', flagIcon: '🇫🇷', tier: 'minor' },
  ],
  territoryMap: {
    'JP':'jpn','KR':'kor_n','KP':'jpn',
    'TH':'tha',
    'CN':'chn','TW':'chn','HK':'jpn','MO':'jpn',
    'US':'usa','PH':'usa','GU':'usa','MP':'usa','AS':'usa','UM':'usa','PW':'usa',
    'GB':'gbr','IE':'gbr','MY':'gbr','SG':'gbr','BN':'gbr','MM':'gbr','LK':'gbr','BT':'gbr','NP':'gbr',
    'FJ':'gbr','SB':'gbr','TO':'gbr','KI':'gbr','VU':'gbr',
    'AU':'aus','PG':'aus','NF':'aus','NZ':'aus','CK':'aus','NU':'aus','HM':'aus',
    'RU':'sov','KZ':'sov','UZ':'sov','TM':'sov','KG':'sov','TJ':'sov','AZ':'sov','AM':'sov','GE':'sov',
    'IN':'ind','PK':'ind','BD':'ind',
    'NL':'nld','ID':'nld',
    'FR':'fra','VN':'fra','LA':'fra','KH':'fra','NC':'fra','PF':'fra',
    '-1':'usa',
  },
};
